name: github_graphql_client
description: Github client using Github API V4 (GraphQL)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  oauth2: ^1.6.1
  url_launcher: ^5.4.10
  gql: ^0.12.3
  gql_exec: ^0.2.4
  gql_link: ^0.3.0
  gql_http_link: ^0.2.9
  window_to_front:
    path: '../window_to_front'
  fluttericon: ^1.0.7

# Note the path specified for the window_to_front dependency: because this is a local package
# instead of one published to pub.dev, you specify a path instead of a version number.

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.10.0
  gql_build: ^0.0.11


flutter:
  uses-material-design: true
